### PR TITLE
Retraining with distortion #229

### PR DESCRIPTION
**Pull request by deepak-matroid**
cd ~/serving
git pull origin
git checkout retraining_experiments
cd tensorflow
git pull origin
git checkout retraining_experiments

Does increasing retraining time by a bit (retraining script takes almost 2x of one without distortion)

#Try to use retrain model with the extra flags for distortion
--store_distortions=True (To statically store the distortions)
--distortion_multiplier=1 (Number of Distorted images to use)
--flip_left_right=True (To flip images horizontally)
--random_scale=10 (upto 10% re-scaling while maintaining centre)
--random_crop=10 (upto 10% croping at the margins)
--random_brightness=10

### CODE REVIEW

**Comment by deepak-matroid** [comment]
To test end to end-- 

Complete the steps in the post above.
Then, update the matroid source code to update main_tensorflow.py
~~~~~~
cd ~/matroid
git fetch origin retraining_with_distortion
git checkout retraining_with_distortion
./restart.sh
~~~~~~~

Now, you should be able to train a model normally. Verify at the backend, ~/matroid/generator/datasets/<>/train.sh is passing distortion parameters

**Comment by deepak-matroid** [comment]
@dong-matroid Should we have a config file to set these parameters instead of hard coding them in?

**Comment by rezazadeh** [comment]
Why is there only one file changed in this PR?

**Comment by dong-matroid** [comment]
@deepak-matroid yes, please have a config file with these parameters, so that main_tensorflow.py can read and launch retrain with them.

**Comment by dong-matroid** [comment]
LGTM, thx @deepak-matroid

**Pull request merged**
